package com.gratex.tools.pp.io.vrt;

import com.gratex.tools.pp.core.PPPart;

/**
 * Caution, this class was generated by pp-codegen.jar, thus it shouldn't be altered manually.
 *
 * @source: pp_structure.xlsx
 * @time: 2023-12-21T10:55:04.095+01:00[Europe/Bratislava]
 * @author mkrajcovicux
 */
public class VRTFooter extends PPPart {

	private String dataSentencesCount;
	private String dataSentencesAmount;

	public void setDataSentencesCount(String dataSentencesCount) {
		this.dataSentencesCount = dataSentencesCount;
	}

	public String getDataSentencesCount() {
		return dataSentencesCount;
	}

	public void setDataSentencesAmount(String dataSentencesAmount) {
		this.dataSentencesAmount = dataSentencesAmount;
	}

	public String getDataSentencesAmount() {
		return dataSentencesAmount;
	}

}