package com.gratex.tools.pp.io.vrt;

import com.gratex.tools.pp.core.PPHeader;

/**
 * Caution, this class was generated by pp-codegen.jar, thus it shouldn't be altered manually.
 *
 * @source: pp_structure.xlsx
 * @time: 2023-12-21T10:55:04.094+01:00[Europe/Bratislava]
 * @author mkrajcovicux
 */
public class VRTHeader extends PPHeader {

	private String senderCode;
	private String iban;
	private String sender;
	private String street;
	private String buildingNumber;
	private String municipality;
	private String postOfficePostalCode;
	private String stampNumber;
	private String dateReceived;
	private String receivedVoucherCount;
	private String totalAmountRemitted;
	private String totalPriceRemitted;
	private String voucherReceiveDate;
	private String voucherValidityDate;
	private String voucherIssueDate;
	private String unpaidAmountAttributionDate;
	private String unpaidVouchersCount;
	private String returnedPrice;
	private String e2eReference;

	public void setSenderCode(String senderCode) {
		this.senderCode = senderCode;
	}

	public String getSenderCode() {
		return senderCode;
	}

	public void setIban(String iban) {
		this.iban = iban;
	}

	public String getIban() {
		return iban;
	}

	public void setSender(String sender) {
		this.sender = sender;
	}

	public String getSender() {
		return sender;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	public String getStreet() {
		return street;
	}

	public void setBuildingNumber(String buildingNumber) {
		this.buildingNumber = buildingNumber;
	}

	public String getBuildingNumber() {
		return buildingNumber;
	}

	public void setMunicipality(String municipality) {
		this.municipality = municipality;
	}

	public String getMunicipality() {
		return municipality;
	}

	public void setPostOfficePostalCode(String postOfficePostalCode) {
		this.postOfficePostalCode = postOfficePostalCode;
	}

	public String getPostOfficePostalCode() {
		return postOfficePostalCode;
	}

	public void setStampNumber(String stampNumber) {
		this.stampNumber = stampNumber;
	}

	public String getStampNumber() {
		return stampNumber;
	}

	public void setDateReceived(String dateReceived) {
		this.dateReceived = dateReceived;
	}

	public String getDateReceived() {
		return dateReceived;
	}

	public void setReceivedVoucherCount(String receivedVoucherCount) {
		this.receivedVoucherCount = receivedVoucherCount;
	}

	public String getReceivedVoucherCount() {
		return receivedVoucherCount;
	}

	public void setTotalAmountRemitted(String totalAmountRemitted) {
		this.totalAmountRemitted = totalAmountRemitted;
	}

	public String getTotalAmountRemitted() {
		return totalAmountRemitted;
	}

	public void setTotalPriceRemitted(String totalPriceRemitted) {
		this.totalPriceRemitted = totalPriceRemitted;
	}

	public String getTotalPriceRemitted() {
		return totalPriceRemitted;
	}

	public void setVoucherReceiveDate(String voucherReceiveDate) {
		this.voucherReceiveDate = voucherReceiveDate;
	}

	public String getVoucherReceiveDate() {
		return voucherReceiveDate;
	}

	public void setVoucherValidityDate(String voucherValidityDate) {
		this.voucherValidityDate = voucherValidityDate;
	}

	public String getVoucherValidityDate() {
		return voucherValidityDate;
	}

	public void setVoucherIssueDate(String voucherIssueDate) {
		this.voucherIssueDate = voucherIssueDate;
	}

	public String getVoucherIssueDate() {
		return voucherIssueDate;
	}

	public void setUnpaidAmountAttributionDate(String unpaidAmountAttributionDate) {
		this.unpaidAmountAttributionDate = unpaidAmountAttributionDate;
	}

	public String getUnpaidAmountAttributionDate() {
		return unpaidAmountAttributionDate;
	}

	public void setUnpaidVouchersCount(String unpaidVouchersCount) {
		this.unpaidVouchersCount = unpaidVouchersCount;
	}

	public String getUnpaidVouchersCount() {
		return unpaidVouchersCount;
	}

	public void setReturnedPrice(String returnedPrice) {
		this.returnedPrice = returnedPrice;
	}

	public String getReturnedPrice() {
		return returnedPrice;
	}

	public void setE2eReference(String e2eReference) {
		this.e2eReference = e2eReference;
	}

	public String getE2eReference() {
		return e2eReference;
	}

}