package com.gratex.tools.pp.io.vrt;

import static java.util.stream.Collectors.toList;

import java.io.IOException;
import java.nio.charset.Charset;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

import com.gratex.tools.pp.utils.CharSequenceIterator;
import com.gratex.tools.pp.core.DataIntegrityViolation;
import com.gratex.tools.pp.core.FileParser;

/**
 * Caution, this class was generated by pp-codegen.jar, thus it shouldn't be altered manually.
 *
 * @source: pp_structure.xlsx
 * @time: 2023-12-21T10:55:04.095+01:00[Europe/Bratislava]
 * @author mkrajcovicux
 */
public class VRTParser implements FileParser<VRTFile> {

	@Override
	public VRTFile parse(Path source, Charset encoding) throws IOException {
		List<String> lines = Files.readAllLines(source, encoding);
		lines.removeIf(e -> e.trim().isEmpty());

		try {
			VRTHeader header = parseHeader(lines.remove(0));
			VRTFooter footer = parseFooter(lines.remove(lines.size() - 1));
			List<VRTRecord> body = parseBody(lines);
			return new VRTFile(header, body, footer);

		} catch (DataIntegrityViolation div) {
			throw new IOException("data integrity violation", div);
		}
	}

	VRTHeader parseHeader(String line) {
		CharSequenceIterator sequencer = new CharSequenceIterator(line);

		VRTHeader header = new VRTHeader();
		header.setCode(sequencer.next(1));
		header.setSenderCode(sequencer.next(4));
		header.setIban(sequencer.next(34));
		header.setSender(sequencer.next(28));
		header.setStreet(sequencer.next(20));
		header.setBuildingNumber(sequencer.next(7));
		header.setMunicipality(sequencer.next(20));
		header.setPostOfficePostalCode(sequencer.next(5));
		header.setSerialNumberIn12M(sequencer.next(4));
		header.setStampNumber(sequencer.next(6));
		header.setDateReceived(sequencer.next(10));
		header.setReceivedVoucherCount(sequencer.next(6));
		header.setTotalAmountRemitted(sequencer.next(13));
		header.setTotalPriceRemitted(sequencer.next(10));
		header.setVoucherReceiveDate(sequencer.next(10));
		header.setVoucherValidityDate(sequencer.next(10));
		header.setVoucherIssueDate(sequencer.next(10));
		header.setUnpaidAmountAttributionDate(sequencer.next(10));
		header.setUnpaidVouchersCount(sequencer.next(6));
		header.setReturnedPrice(sequencer.next(13));
		header.setE2eReference(sequencer.next(35));

		validateRemainingContent(sequencer);
		return header;
	}

	List<VRTRecord> parseBody(List<String> lines) {
		return lines.stream()
		.map(this::parseRecord)
		.collect(toList());
	}

	private VRTRecord parseRecord(String line) {
		CharSequenceIterator sequencer = new CharSequenceIterator(line);

		VRTRecord bodyLine = new VRTRecord();
		bodyLine.setCode(sequencer.next(1));
		bodyLine.setRecipientFullName(sequencer.next(30));
		bodyLine.setRecipientOtherIdentifier(sequencer.next(30));
		bodyLine.setStreet(sequencer.next(28));
		bodyLine.setBuildingNumber(sequencer.next(10));
		bodyLine.setMunicipality(sequencer.next(30));
		bodyLine.setPostOfficePostalCode(sequencer.next(5));
		bodyLine.setAddressNote(sequencer.next(30));
		bodyLine.setRecipientCode(sequencer.next(30));
		bodyLine.setAmount(sequencer.next(10));
		bodyLine.setFileNumber(sequencer.next(5));
		bodyLine.setReasonUnpaid(sequencer.next(21));

		validateRemainingContent(sequencer);
		return bodyLine;
	}

	VRTFooter parseFooter(String line) {
		CharSequenceIterator sequencer = new CharSequenceIterator(line);

		VRTFooter footer = new VRTFooter();
		footer.setCode(sequencer.next(1));
		footer.setDataSentencesCount(sequencer.next(6));
		footer.setDataSentencesAmount(sequencer.next(13));

		validateRemainingContent(sequencer);
		return footer;
	}

	private void validateRemainingContent(CharSequenceIterator sequencer) {
		if (sequencer.hasMore()) {
			throw new DataIntegrityViolation("Unexpected unparsable content");
		}
	}

}
