package com.gratex.tools.pp.io.vrt;

import com.gratex.tools.pp.core.PPPart;

/**
 * Caution, this class was generated by pp-codegen.jar, thus it shouldn't be altered manually.
 *
 * @source: pp_structure.xlsx
 * @time: 2023-12-21T10:55:04.094+01:00[Europe/Bratislava]
 * @author mkrajcovicux
 */
public class VRTRecord extends PPPart {

	private String recipientFullName;
	private String recipientOtherIdentifier;
	private String street;
	private String buildingNumber;
	private String municipality;
	private String postOfficePostalCode;
	private String addressNote;
	private String recipientCode;
	private String amount;
	private String fileNumber;
	private String reasonUnpaid;

	public void setRecipientFullName(String recipientFullName) {
		this.recipientFullName = recipientFullName;
	}

	public String getRecipientFullName() {
		return recipientFullName;
	}

	public void setRecipientOtherIdentifier(String recipientOtherIdentifier) {
		this.recipientOtherIdentifier = recipientOtherIdentifier;
	}

	public String getRecipientOtherIdentifier() {
		return recipientOtherIdentifier;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	public String getStreet() {
		return street;
	}

	public void setBuildingNumber(String buildingNumber) {
		this.buildingNumber = buildingNumber;
	}

	public String getBuildingNumber() {
		return buildingNumber;
	}

	public void setMunicipality(String municipality) {
		this.municipality = municipality;
	}

	public String getMunicipality() {
		return municipality;
	}

	public void setPostOfficePostalCode(String postOfficePostalCode) {
		this.postOfficePostalCode = postOfficePostalCode;
	}

	public String getPostOfficePostalCode() {
		return postOfficePostalCode;
	}

	public void setAddressNote(String addressNote) {
		this.addressNote = addressNote;
	}

	public String getAddressNote() {
		return addressNote;
	}

	public void setRecipientCode(String recipientCode) {
		this.recipientCode = recipientCode;
	}

	public String getRecipientCode() {
		return recipientCode;
	}

	public void setAmount(String amount) {
		this.amount = amount;
	}

	public String getAmount() {
		return amount;
	}

	public void setFileNumber(String fileNumber) {
		this.fileNumber = fileNumber;
	}

	public String getFileNumber() {
		return fileNumber;
	}

	public void setReasonUnpaid(String reasonUnpaid) {
		this.reasonUnpaid = reasonUnpaid;
	}

	public String getReasonUnpaid() {
		return reasonUnpaid;
	}

}