package com.gratex.tools.pp.io.ppe;

import com.gratex.tools.pp.core.PPHeader;

/**
 * Caution, this class was generated by pp-codegen.jar, thus it shouldn't be altered manually.
 *
 * @source: pp_structure.xlsx
 * @time: 2023-12-21T10:55:04.073+01:00[Europe/Bratislava]
 * @author mkrajcovicux
 */
public class PPEHeader extends PPHeader {

	private String iban1;
	private String iban2;
	private String fileCreated;
	private String voucherValidity;
	private String diacriticsCode;
	private String testLetterForDiacriticsCode;
	private String payOutDate;

	public void setIban1(String iban1) {
		this.iban1 = iban1;
	}

	public String getIban1() {
		return iban1;
	}

	public void setIban2(String iban2) {
		this.iban2 = iban2;
	}

	public String getIban2() {
		return iban2;
	}

	public void setFileCreated(String fileCreated) {
		this.fileCreated = fileCreated;
	}

	public String getFileCreated() {
		return fileCreated;
	}

	public void setVoucherValidity(String voucherValidity) {
		this.voucherValidity = voucherValidity;
	}

	public String getVoucherValidity() {
		return voucherValidity;
	}

	public void setDiacriticsCode(String diacriticsCode) {
		this.diacriticsCode = diacriticsCode;
	}

	public String getDiacriticsCode() {
		return diacriticsCode;
	}

	public void setTestLetterForDiacriticsCode(String testLetterForDiacriticsCode) {
		this.testLetterForDiacriticsCode = testLetterForDiacriticsCode;
	}

	public String getTestLetterForDiacriticsCode() {
		return testLetterForDiacriticsCode;
	}

	public void setPayOutDate(String payOutDate) {
		this.payOutDate = payOutDate;
	}

	public String getPayOutDate() {
		return payOutDate;
	}

}