package com.gratex.tools.pp.io.ppe;

import static java.util.stream.Collectors.toList;

import java.io.IOException;
import java.nio.charset.Charset;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

import com.gratex.tools.pp.utils.CharSequenceIterator;
import com.gratex.tools.pp.core.DataIntegrityViolation;
import com.gratex.tools.pp.core.FileParser;

/**
 * Caution, this class was generated by pp-codegen.jar, thus it shouldn't be altered manually.
 *
 * @source: pp_structure.xlsx
 * @time: 2023-12-21T10:55:04.077+01:00[Europe/Bratislava]
 * @author mkrajcovicux
 */
public class PPEParser implements FileParser<PPEFile> {

	@Override
	public PPEFile parse(Path source, Charset encoding) throws IOException {
		List<String> lines = Files.readAllLines(source, encoding);
		lines.removeIf(e -> e.trim().isEmpty());

		try {
			PPEHeader header = parseHeader(lines.remove(0));
			PPEFooter footer = parseFooter(lines.remove(lines.size() - 1));
			List<PPERecord> body = parseBody(lines);
			return new PPEFile(header, body, footer);

		} catch (DataIntegrityViolation div) {
			throw new IOException("data integrity violation", div);
		}
	}

	PPEHeader parseHeader(String line) {
		CharSequenceIterator sequencer = new CharSequenceIterator(line);

		PPEHeader header = new PPEHeader();
		header.setCode(sequencer.next(1));
		header.setIban1(sequencer.next(34));
		header.setIban2(sequencer.next(34));
		header.setFileCreated(sequencer.next(8));
		header.setSerialNumberIn12M(sequencer.next(4));
		header.setVoucherValidity(sequencer.next(2));
		header.setDiacriticsCode(sequencer.next(3));
		header.setTestLetterForDiacriticsCode(sequencer.next(1));
		header.setPayOutDate(sequencer.next(8));

		validateRemainingContent(sequencer);
		return header;
	}

	List<PPERecord> parseBody(List<String> lines) {
		return lines.stream()
		.map(this::parseRecord)
		.collect(toList());
	}

	private PPERecord parseRecord(String line) {
		CharSequenceIterator sequencer = new CharSequenceIterator(line);

		PPERecord bodyLine = new PPERecord();
		bodyLine.setCode(sequencer.next(1));
		bodyLine.setRecipientFullName(sequencer.next(30));
		bodyLine.setRecipientOtherIdentifier(sequencer.next(30));
		bodyLine.setStreet(sequencer.next(28));
		bodyLine.setBuildingNumber(sequencer.next(10));
		bodyLine.setMunicipality(sequencer.next(30));
		bodyLine.setPostOfficePostalCode(sequencer.next(5));
		bodyLine.setAddressNote(sequencer.next(30));
		bodyLine.setAmount(sequencer.next(10));
		bodyLine.setPrice(sequencer.next(7));
		bodyLine.setServiceCode(sequencer.next(3));
		bodyLine.setRecipientCode(sequencer.next(30));
		bodyLine.setPurpose(sequencer.next(30));
		bodyLine.setEmail(sequencer.next(50));
		bodyLine.setTelephone(sequencer.next(20));

		// commented-out on purpose until we find out why .ppe data sentences
		// differ in length in comparison to currently valid documentation
		// validateRemainingContent(sequencer);
		return bodyLine;
	}

	PPEFooter parseFooter(String line) {
		CharSequenceIterator sequencer = new CharSequenceIterator(line);

		PPEFooter footer = new PPEFooter();
		footer.setCode(sequencer.next(1));
		footer.setVoucherCount(sequencer.next(5));
		footer.setTotalAmount(sequencer.next(13));
		footer.setTotalPrice(sequencer.next(10));
		footer.setSum(sequencer.next(13));

		validateRemainingContent(sequencer);
		return footer;
	}

	private void validateRemainingContent(CharSequenceIterator sequencer) {
		if (sequencer.hasMore()) {
			throw new DataIntegrityViolation("Unexpected unparsable content");
		}
	}

}
