package com.gratex.tools.pp.io.pod;

import com.gratex.tools.pp.core.PPPart;

/**
 * Caution, this class was generated by pp-codegen.jar, thus it shouldn't be altered manually.
 *
 * @source: pp_structure.xlsx
 * @time: 2023-12-21T10:55:04.089+01:00[Europe/Bratislava]
 * @author mkrajcovicux
 */
public class PODFooter extends PPPart {

	private String voucherCount;
	private String totalAmount;
	private String totalPrice;
	private String sum;

	public void setVoucherCount(String voucherCount) {
		this.voucherCount = voucherCount;
	}

	public String getVoucherCount() {
		return voucherCount;
	}

	public void setTotalAmount(String totalAmount) {
		this.totalAmount = totalAmount;
	}

	public String getTotalAmount() {
		return totalAmount;
	}

	public void setTotalPrice(String totalPrice) {
		this.totalPrice = totalPrice;
	}

	public String getTotalPrice() {
		return totalPrice;
	}

	public void setSum(String sum) {
		this.sum = sum;
	}

	public String getSum() {
		return sum;
	}

}