package com.gratex.tools.pp.io.pod;

import com.gratex.tools.pp.core.PPHeader;

/**
 * Caution, this class was generated by pp-codegen.jar, thus it shouldn't be altered manually.
 *
 * @source: pp_structure.xlsx
 * @time: 2023-12-21T10:55:04.089+01:00[Europe/Bratislava]
 * @author mkrajcovicux
 */
public class PODHeader extends PPHeader {

	private String iban1;
	private String stampNumber;
	private String dayReceived;
	private String monthReceived;
	private String yearReceived;

	public void setIban1(String iban1) {
		this.iban1 = iban1;
	}

	public String getIban1() {
		return iban1;
	}

	public void setStampNumber(String stampNumber) {
		this.stampNumber = stampNumber;
	}

	public String getStampNumber() {
		return stampNumber;
	}

	public void setDayReceived(String dayReceived) {
		this.dayReceived = dayReceived;
	}

	public String getDayReceived() {
		return dayReceived;
	}

	public void setMonthReceived(String monthReceived) {
		this.monthReceived = monthReceived;
	}

	public String getMonthReceived() {
		return monthReceived;
	}

	public void setYearReceived(String yearReceived) {
		this.yearReceived = yearReceived;
	}

	public String getYearReceived() {
		return yearReceived;
	}

}