package com.gratex.tools.pp.core;

import static java.util.Objects.nonNull;

import java.nio.file.Path;

/**
 * Caution, this class was generated by pp-codegen.jar, thus it shouldn't be altered manually.
 *
 * @source: pp_structure.xlsx
 * @time: 2023-12-21T10:55:04.100+01:00[Europe/Bratislava]
 * @author mkrajcovicux
 */
public enum FileType {

	PPE(".ppe"),
	POD(".pod"),
	VRT(".vrt");

	private final String extension;

	private FileType(String extension) {
		this.extension = extension;
	}

	public String getFileExtension() {
		return this.extension;
	}

	public boolean isExtensionOn(Path path) {
		if (nonNull(path)) {
			String file = String.valueOf(path.getFileName());
			return file.endsWith(extension);
		}
		return false;
	}

}
